# Generated by Django 4.2.5 on 2025-05-28 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='involved_users',
            field=models.ManyToManyField(related_name='involved_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
