# Generated by Django 4.2.5 on 2025-05-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expense_involved_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='involved_users',
        ),
    ]
